= Internal References and URLs
:page-subtitle: AdocWiki
:page-tags: link url xref
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Links to internal references

[TIP]
====
“Internal references” are links to other documents inside the project.
====

While authoring (writing AsciiDoc documents in a text editor), we often link to other documents.
In these cases, use `xref` (and not `link`) to reference those other documents.
Keep the `.adoc` extension so they are navigable normaly in the text editor.
AdocWiki (through Asciidoctor really) will make sure the converted pages have links with `.html` so they work correctly when viewed in a web browser.
See the next example:

.A document referencing another document
[source,asciidoc]
----
Jump to the xref:../intro.adoc[Intro] page.
----

And it will result in HTML similar to this:

.Resulting HTML from the previous AsciiDoc example
[source,html]
----
<p>
  Jump to the <a href="../intro.html" >Intro</a> page.
</p>
----

Note how the ``a``'s `href` attribute value ends with `.html`, thus allowing proper navigation between pages.
